services:
  - type: web
    name: rembg-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: USE_MOCK_MODE
        value: false
